# app/config/security.yml

security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
            database:
                entity: { class: Ens\JobeetBundle\Entity\User, property: username }

    encoders:
            Ens\JobeetBundle\Entity\User: sha512
#
#    providers:
#      in_memory:
#          memory:
#              users:
#                  admin: { password: adminpass, roles: ROLE_ADMIN }
#
#    encoders:
#            Symfony\Component\Security\Core\User\User: plaintext